export const DEFAULT_PROFILE = {
  name: 'LeLeLe',
  title: '全栈开发工程师 / 技术博主 / 开源爱好者',
  bio: '👋 你好！我是一名热爱技术的全栈开发者，专注于构建优雅高效的Web应用。擅长React/Vue前端开发和Spring Boot后端架构设计，对3D可视化、AI应用有浓厚兴趣。热衷于开源贡献和技术分享，相信代码可以改变世界。在编程之外，喜欢探索新技术、写技术博客、参与开发者社区。',
  avatarUrl: '/picture/avatar.jpg',
  resumeUrl: '',
  github: 'https://github.com/lelele-lswl',
  email: '3054793058@qq.com',
  bilibili: 'https://space.bilibili.com/493506164',
  location: '中国 · 正在远程工作中',
  motto: '保持好奇，持续学习，用代码创造价值 ✨',
  education: '计算机科学与技术专业',
  experience: '1年+ 全栈开发经验',
  interests: ['Web开发', '开源项目', '技术写作', '3D可视化', '人工智能'],
}

export const DEFAULT_SKILLS = [
  { name: 'React', category: 'Frontend', level: 90, icon: 'SiReact' },
  { name: 'Vue.js', category: 'Frontend', level: 85, icon: 'SiVuedotjs' },
  { name: 'TypeScript', category: 'Frontend', level: 88, icon: 'SiTypescript' },
  { name: 'JavaScript', category: 'Frontend', level: 95, icon: 'SiJavascript' },
  { name: 'HTML/CSS', category: 'Frontend', level: 92, icon: 'SiHtml5' },
  { name: 'Three.js', category: 'Frontend', level: 75, icon: 'SiThreedotjs' },
  { name: 'TailwindCSS', category: 'Frontend', level: 88, icon: 'SiTailwindcss' },
  { name: 'Spring Boot', category: 'Backend', level: 85, icon: 'SiSpringboot' },
  { name: 'Java', category: 'Backend', level: 88, icon: 'SiOpenjdk' },
  { name: 'Node.js', category: 'Backend', level: 82, icon: 'SiNodedotjs' },
  { name: 'Python', category: 'Backend', level: 78, icon: 'SiPython' },
  { name: 'MySQL', category: 'Backend', level: 80, icon: 'SiMysql' },
  { name: 'Redis', category: 'Backend', level: 72, icon: 'SiRedis' },
  { name: 'Docker', category: 'DevOps', level: 78, icon: 'SiDocker' },
  { name: 'Git', category: 'DevOps', level: 90, icon: 'SiGit' },
  { name: 'Linux', category: 'DevOps', level: 75, icon: 'SiLinux' },
  { name: 'Nginx', category: 'DevOps', level: 70, icon: 'SiNginx' },
  { name: 'AWS', category: 'DevOps', level: 65, icon: 'SiAmazon' },
]

export const DEFAULT_PROJECTS = [
  {
    title: 'SlaySeed',
    description: '杀戮尖塔种子分享与查询平台。实现docker-compose编排，实现ci/cd自动化。解决生产项目部署加速。',
    techStack: 'React, Spring Boot, OpenAI API, WebSocket, MySQL',
    githubUrl: 'https://github.com/lelele-lswl/slayseed',
    previewUrl: '',
    imageUrl: '/picture/slayseed.png',
    sortOrder: 1,
  },
  {
    title: 'Shool Take Out',
    description: '基于SpringBoot+Vue开发外卖平台，分管理后台与小程序。运用Redis缓存菜品、存储购物车，分布式锁防止超卖；WebSocket推送订单消息，定时任务自动关闭超时订单。集成JWT权限、OSS文件上传、微信支付，AOP统一处理公共字段与全局异常。',
    techStack: 'Vue.js, Node.js, ECharts, MongoDB, Socket.io',
    githubUrl: 'https://github.com/lelele-lswl/-',
    previewUrl: '',
    imageUrl: '/picture/take-out.png',
    sortOrder: 2,
  },
  {
    title: '3D Portfolio Website',
    description: '个人作品展示网站。ai+prompt提示词工程，基于Three.js构建3D场景，使用InstancedMesh + BufferGeometry实现万级粒子系统的高性能渲染，Raycaster实现3D模型拾取与交互响应，基于PBR材质与动态光源实现物理级光影效果；Framer Motion驱动页面过渡动画，结合React lazy + Suspense实现3D资源的按需加载与性能优化。',
    techStack: 'React, Three.js, Framer Motion, TailwindCSS',
    githubUrl: 'https://github.com/lelele-lswl/Personal-Technical-Blog-Website/tree/master',
    previewUrl: '',
    imageUrl: '/picture/3DPortfolioWebsite.png',
    sortOrder: 3,
  },
  {
    title: 'Book Node Manager',
    description: '基于Spring Cloud微服务架构的笔记管理平台。学校实习项目，多人协作完成，作为核心负责人完成整体的项目架构。拥有较强的团队合作能力。',
    techStack: 'Spring Cloud, Docker, Kubernetes, Redis, RabbitMQ',
    githubUrl: 'https://github.com/lelele-lswl/BookNoteManage',
    previewUrl: '',
    imageUrl: '/picture/book.png',
    sortOrder: 4,
  },
]

export const NAV_ITEMS = [
  { label: '首页', href: '#hero' },
  { label: '关于', href: '#about' },
  { label: '技能', href: '#skills' },
  { label: '项目', href: '#projects' },
  { label: '留言板', href: '#guestbook' },
]